name: graph_embedding
channels:
  - defaults
dependencies:
  - python=3.7
  - tensorflow=1.14
  - numpy=1.21.6
  - pandas=1.3.5
  - scikit-learn=1.0.2
  - matplotlib=3.5.3
  - networkx=2.6.3
  - h5py=2.10.0
  - pip
  - pip:
    - deepctr==0.9.3
    - gensim==4.2.0
    - fastdtw==0.3.4